### ISSUE TITLE
Support Omron M400 IT

### ISSUE THREAD

**Issue by probonopd** [LazyT/obpm#1]
It it possible to use the Omron M400 IT? The device looks _very_ similar.

**Comment by LazyT** [comment]
With some support from device owners I guess yes. ;-)

Can you please post the usb device id for the M400IT?

**Comment by probonopd** [comment]
The device identifies itself as 
```
Bus 001 Device 005: ID 0590:0090 Omron Corp.
```
and I was able to transfer the following data (probably test data?) from a brand new device:
```
user;date;time;sys;dia;pulse
1;01.01.14;00:00;155;093;090
```
So it looks like the Omron M400 IT is already supported, which is great. I will observe it some more and if no issues arise, it can be added to the documentation and UI strings.

**Comment by LazyT** [comment]
Different devices share the same product id? That sucks, because I can't distinguish them...

**Comment by probonopd** [comment]
Ì wouldn't be surprised if there was a command in the protocol that would deliver the product name...

**Comment by probonopd** [comment]
Indeed the wrong product name is currently displayed.

![screenshot2](https://cloud.githubusercontent.com/assets/2480569/12009657/ac19d766-ac81-11e5-8e5e-53c4c972d7ec.png)

But hey, it (mostly) works anyway!

**Comment by LazyT** [comment]
M400IT fully supported in next release.

Thanks for testing!

**Comment by probonopd** [comment]
Perhaps it is worth mentioning that even in the official software the user has to select the device type...
