### ISSUE TITLE
Support for the M10-IT

### ISSUE THREAD

**Issue by ned14** [LazyT/obpm#10]
Looks to be a standard Omron blood pressure monitor USB with the following VID and PID:

```
HID\VID_0590&PID_0028&REV_0201
```

There is an argument in favour of attempting to work with all VIDs of 0590 with a warning that it is an untested device :)

**Comment by LazyT** [comment]
Did you try to patch the id and test the communication? Just because it's an Omron doesn't mean it speaks the same protocol. ;)

The supported devices also have 60 or 100 memory slots, the M10 has 84 - it will not work correctly...

**Comment by rudi48** [comment]
Hello LazyT,
I have also a M10-IT and haved used under Ubuntu 14.04 this
[open source software libomron](https://github.com/openyou/libomron)
So I assume, the protocol should be documented there.
Your software is much more useful, so it would be helpful to have
also the M10 protocol implemented.

By the way, the M10-IT has 2 x 84 memory slots, for user A and B.
Regards, Rudolf

**Comment by rudi48** [comment]
Hello LazyT,
I have also a M10-IT and haved used under Ubuntu 14.04 this
[open source software libomron](https://github.com/openyou/libomron)
So I assume, the protocol should be documented there.
Your software is much more useful, so it would be helpful to have
also the M10 protocol implemented.

By the way, the M10-IT has 2 x 84 memory slots, for user A and B.
Regards, Rudolf

**Comment by rudi48** [comment]
Hello LazyT,
In order to help with details, I have a web page describing the use of libomron:
[Omron M10, use of libomron](http://www.rudiswiki.de/wiki9/BloodPressureMonitor24h?highlight=%28m10%29#Application_Software)

For my understanding the omron protocol is defined in the project tree in
`/libomron-master/include/libomron/omron.h`

Regards, Rudolf

**Comment by LazyT** [comment]
When libomron works then the protocol is different. I tried this [first](https://github.com/openyou/libomron/issues/24) before I wrote my own stuff.

Sorry, but there is not time at the moment as you can see at the commits. Beside that it's difficult to implement things without the possibility to test.

**Comment by rudi48** [comment]
Hello LazyT,
Thank you for the answer.
When I have time, I will have a look for the protocol.
Regards, Rudolf

**Comment by pabloinigoblasco** [comment]
Hello, something new here?

**Comment by LazyT** [comment]
I've no plans to implement this device (or any other I don't own).

Maybe you can contact @rudi48?

**Comment by davidhedlund** [comment]
Omron M10-IT is [discontinued](https://www.omron-healthcare.com/en/products/bloodpressuremonitoring).
