### ISSUE TITLE
Feature request - record irregular heartbeats

### ISSUE THREAD

**Issue by thisandre** [LazyT/obpm#14]
Omron logs the irregular heartbeats in the bpm.  Is it possible to transfer these to the database and to show them in the heart rate table with some dedicated symbol (as Omron did in their health management software for the older types of bpm)?

**Comment by thisandre** [comment]
Does anyone know the message format Omron uses to send the messages over the USB interface?

**Comment by thisandre** [comment]
I sniffed around on the USB interface and found out where Omron hides the 'irregular heartbeat' indication.  It's in word 9 of the record.  In case of an irregular heartbeat, this word becomes Hex 20 or 22.  The word is 00 in normal cases and could be 01 or 00 in case a 'pumping problem occurs'. In that case, word 10 of the record becomes Hex 44 or 48.  It would be useful to plot a dot on top of the heartbeat graph in case the irregular heartbeat occurs.

**Comment by thisandre** [comment]
Hi Thomas, I updated the code and implemented the 'Irregular beat' indication.  Showing it at the bottom of the heartrate graph and made it switchable on/of via the setup-appearance. I exported my existing database to csv and imported this again.  I managed to import 10661 entries successfully. 
As a note: the new information will only be displayed from the new measurements since that specific information from the old measurements is lost. You can contact me and I'll send you the files.

**Comment by 55richard** [comment]
The irregular heartbeat registration would be very useful for me. Will this be implemented?

**Comment by thisandre** [comment]
I implemented it as I told in my previous message.  I never got an answer from LazyT. I run it on Ubuntu but I don't know how to compile it for PC.  I'm also interested in the PC application.  
I never uploaded changes to Github, and first have to find out how this works.

**Comment by LazyT** [comment]
This is now implemented in the successor [UBPM](https://codeberg.org/LazyT/ubpm).
