### ISSUE TITLE
[Cosmetic] Support Retina Macs

### ISSUE THREAD

**Issue by probonopd** [LazyT/obpm#2]
Currently the UI is pixelated on Retina Macs. Probably by using Qt 5.5, Retina Macs would be supported with full resolution.

Not super important, but still nice to have.

http://doc.qt.io/qt-5/highdpi.html
http://stackoverflow.com/questions/34465506/retina-support-in-qt5-on-os-x

**Comment by LazyT** [comment]
Info.plist was missing in the installer, fixed with next release.
