### ISSUE TITLE
Support for even simple CLI

### ISSUE THREAD

**Issue by azyata** [LazyT/obpm#20]
I want to make Rasbperry Pi "software" that after connecting Blood Pressure monitor will download all results and send them (csv file is I think most all-purpouse way) to remote and then parse it and show in Grafana. As out of the box as it is possible. I hope that will help a lot of people achive their goals or make easier to monitor their health.

![image](https://user-images.githubusercontent.com/37910941/47945503-bb4b4100-df02-11e8-9c27-bb17cbbe83dd.png)

I could write systemd service that will execute code when specific device is connected.
Then I need a way to force `obpm` to download entries from device and then export it to csv file (in best case with `--path` flag)

![image](https://user-images.githubusercontent.com/37910941/47945461-73c4b500-df02-11e8-841d-48d463ce189a.png)

**Comment by LazyT** [comment]
I've a small cli for testing.

Maybe it's helpfull to code your own: [obpm-cli.tar.gz](https://github.com/LazyT/obpm/files/2544780/obpm-cli.tar.gz)

**Comment by azyata** [comment]
Thanks!
