### ISSUE TITLE
Bluetooth device support. What would it take?

### ISSUE THREAD

**Issue by bserem** [LazyT/obpm#25]
I see in #23 that Bluetooth is not support at the moment. Would it be possible to add such functionality in the future?

Thanks

**Comment by qqgg231** [comment]
You need to know how to talk with this device via Bluetooth. What to send to receive data.

How to do it is here:
https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale

**Comment by LazyT** [comment]
This is theoretically possible now with the successor [UBPM](https://codeberg.org/LazyT/ubpm).

But someone has to code a device plugin first.
