### ISSUE TITLE
Feature request: Clearing user data

### ISSUE THREAD

**Issue by olivergs** [LazyT/obpm#26]
Just a button somewhere to clear data for specific user

**Comment by thisandre** [comment]
You can export your database to csv format, delete the user entries with Notepad or some other editor and import again in the program, specifying NOT adding it to the existing database.  In that case, a new sql file will be created with the user you left in.

**Comment by olivergs** [comment]
Thanks for the information.

I just wanted to clear the information I imported, so I deleted the sql file and solved my problem.

Anyway, this is a good solution for a "somewhat" advanced user, but I think it adding a button to clear only a specified user in the application preferences could be a very simple addition that could help an average user to access this feature.

I think telling a normal user to export and edit a CSV file is kind of "overkill".

**Comment by LazyT** [comment]
This is implemented now with the successor [UBPM](https://codeberg.org/LazyT/ubpm).
