### ISSUE TITLE
Support 2nd user

### ISSUE THREAD

**Issue by probonopd** [LazyT/obpm#3]
There is a switch on the M400 IT to select user 1 or user 2. While reading data for user 1 works well, data for user 2 is not read correctly.

| user | date     | time  | sys | dia | pulse | 
|------|----------|-------|-----|-----|-------| 
| 1    | 24.12.15 | 21:46 | 140 | 74  | 44    | 
| 1    | 24.12.15 | 22:26 | 148 | 76  | 47    | 
| 1    | 07.02.06 | 07:28 | 280 | 255 | 255   | 

The last line is entirely wrong. There should actually be data for user 2.

**Comment by LazyT** [comment]
Fixed in next release.
