### ISSUE TITLE
Manual data from scratch

### ISSUE THREAD

**Issue by effzett** [LazyT/obpm#8]
obpm crashes if:

1) Start obpm from scratch
2) try to manually insert a value

Reason: Right from start no user is selected. Perhaps user1 should be the default user...

If a user is selected before it works.

System/Version: OSX 10.10.5
origin/master from Github

**Comment by effzett** [comment]
perhaps simply give user1 a check in QAction in mainwindow.ui ?

**Comment by LazyT** [comment]
Should be fixed, Thanks!
